In [ ]:
import pandas as pd

In [133]:
df = pd.read_csv('AAPL_stock_data.csv')

df['updt'] = pd.to_datetime(df['Time'],format= '%Y-%m-%d %H:%M:%S')
df['date'] = pd.to_datetime(df['Time'],format= '%Y-%m-%d %H:%M:%S').dt.date
df['hour'] = pd.to_datetime(df['Time'],format= '%Y-%m-%d %H:%M:%S').dt.hour
df['minute'] = pd.to_datetime(df['Time'],format= '%Y-%m-%d %H:%M:%S').dt.minute
df['3m'] = df['minute']//3
df['grp_3m'] = df['updt'].dt.strftime('%Y%m%d%H')+df['3m'].astype(str)
#df['grp_3m'] = df['grp_3m'].astype(int)

df = df.sort_values(by=['updt'], ascending=True)

temp_df = df.groupby('grp_3m').apply(lambda x: x.iloc[[-1]]).reset_index(drop=True).sort_values(by=['updt'], ascending=True)

temp_df = temp_df.loc[:,['updt','grp_3m','Price']]
temp_df['Opening'] = temp_df['Price'].shift(1)
temp_df['Closing'] = temp_df['Price']

temp_df = temp_df.where(temp_df['Opening'].notna()).dropna()

temp_df['Trend'] = temp_df['Closing'] - temp_df['Opening']

temp_df

,updt,grp_3m,Price,Opening,Closing,Trend
1,2023-09-22 00:05:58.625558,20230922001,174.699997,174.580002,174.699997,0.119995
12,2023-09-22 00:08:59.315957,20230922002,174.839600,174.699997,174.839600,0.139603
13,2023-09-22 00:11:59.801100,20230922003,174.970001,174.839600,174.970001,0.130402
14,2023-09-22 00:14:59.357050,20230922004,174.854996,174.970001,174.854996,-0.115005
15,2023-09-22 00:17:59.321727,20230922005,174.759995,174.854996,174.759995,-0.095001
16,2023-09-22 00:20:59.898716,20230922006,174.710007,174.759995,174.710007,-0.049988
17,2023-09-22 00:23:58.847968,20230922007,174.690002,174.710007,174.690002,-0.020004
18,2023-09-22 00:26:58.902887,20230922008,174.740005,174.690002,174.740005,0.050003
19,2023-09-22 00:29:59.484383,20230922009,174.654999,174.740005,174.654999,-0.085007
2,2023-09-22 00:32:59.498789,202309220010,174.654999,174.654999,174.654999,0.000000
3,2023-09-22 00:35:59.091214,202309220011,174.569901,174.654999,174.569901,-0.085098
4,2023-09-22 00:38:59.697521,202309220012,174.569901,174.569901,174.569901,0.000000
5,2023-09-22 00:41:59.540647,202309220013,174.500000,174.569901,174.500000,-0.069901
6,2023-09-22 00:44:59.130199,202309220014,174.399994,174.500000,174.399994,-0.100006
7,2023-09-22 00:47:59.955247,202309220015,174.395004,174.399994,174.395004,-0.004990
8,2023-09-22 00:50:58.526529,202309220016,174.410004,174.395004,174.410004,0.014999
9,2023-09-22 00:53:59.040913,202309220017,174.380005,174.410004,174.380005,-0.029999
10,2023-09-22 00:56:59.351721,202309220018,174.320007,174.380005,174.320007,-0.059998
11,2023-09-22 00:59:58.765116,202309220019,174.290497,174.320007,174.290497,-0.029510
20,2023-09-22 01:02:59.770464,20230922010,174.190002,174.290497,174.190002,-0.100494
21,2023-09-22 01:05:58.753186,20230922011,174.396393,174.190002,174.396393,0.206390
22,2023-09-22 01:08:58.840896,20230922012,174.514999,174.396393,174.514999,0.118607
23,2023-09-22 01:11:58.561331,20230922013,174.414993,174.514999,174.414993,-0.100006
24,2023-09-22 01:14:59.260376,20230922014,174.404999,174.414993,174.404999,-0.009995
25,2023-09-22 01:17:59.101107,20230922015,174.362000,174.404999,174.362000,-0.042999
26,2023-09-22 01:19:20.328796,20230922016,174.300095,174.362000,174.300095,-0.061905